name: alquran_new
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  adhan: ^2.0.0+1
  after_layout: ^1.2.0
  audioplayers: ^5.2.1
  card_loading: ^0.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  grouped_list: ^5.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  redux: ^5.0.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  slide_countdown: ^1.3.5
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/alquran/
    - assets/json/city/
    - assets/json/detail_alquran/

  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoNaskhArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoNaskhArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
          weight: 700
    - family: Umani
      fonts:
        - asset: assets/fonts/UthmanTN1_Ver07.otf
        - asset: assets/fonts/UthmanTN1B_Ver07.otf
          weight: 700
